# -*- coding: utf-8 -*-
"""project2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hiwKoWCf4kv_FrMrYdVVpydJEoqE-a-I

**Objective**:

The aim of this project is to determine the number of nice (**N**), rainy (**R**), and snowy (**S**) days in the Land of Oz during a 30-day month. We have access to weather data recorded over a 500-day period.

**Data Collection**:

We begin by extracting probabilities from the provided data for the three distinct weather types. Combination such as "Snow and Rain" (**SR**), "Rain and Rain" (**RR**), and "Nice and Snow" (**NS**) are possible. This leads to the following sets: '**SS**', '**SR**', '**SN**', '**RR**', '**RS**', '**RN**', '**NR**', and '**NS**'.

**Data Processing**:

Eight counters are initialized to zero, each representing a specific weather set. The program iterates through the 500 days of data in pairs to determine the frequency of each set's occurrence. Once the counts for each pair are obtained, the script displays the number of occurrences for each distinct combination.
"""

days = "SSRNRNSSSSSSNRSNSSRNSRNSSSNSRRRNSSSNRRSSSSNRSSNSRRRRRRNSSSSSRRRSNSNRRRRSRSRNSNSRRNRRNRSSNSRNRNSSRRSRNSSSNRSRRSSNRSNRRNSSSSNSSNSRSRRNSSNSSRNSSRRNRRRSRNRRRNSSSNRNSRNSNRNRSSSRSSNRSSSNSSSSSSNSSSNSNSRRNRNRRRRSRRRSSSSNRRSSSSRSRRRNRRRSSSSRRNRRRSRSSRRRRSSRNRRRRRRNSSRNRSSSNRNSNRRRRNRRRNRSNRRNSRRSNRRRRSSSRNRRRNSNSSSSSRRRRSRNRSSRRRRSSSRRRNRNRRRSRSRNSNSSRRRRRNSNRNSNRRNRRRRRRSSSNRSSRSNRSSSNSNRNSNSSSNRRSRRRNRRRRNRNRSSSNSRSNRNRRSNRRNSRSSSRNSRRSSNSRRRNRRSNRRNSSSSSNRNSSSSSSSNRNSRRRNSSRRRNSSSNRRSRNSSRRNRRNRSNRRRR "

# Initialize counters for 'SS', 'SR', 'SN', 'RR', 'RS', 'RN', 'NR', and 'NS'.
count_SS = 0
count_SR = 0
count_SN = 0
count_RR = 0
count_RS = 0
count_RN = 0
count_NR = 0
count_NS = 0

j = 0
# Loop through the string and check for pairs
for i in range(0, len(days)):
  j = j + 1
  pair = days[i:i+2]
  if pair == "SS":
    count_SS += 1
  elif pair == "SR":
    count_SR += 1
  elif pair == "SN":
    count_SN += 1
  elif pair == "RR":
    count_RR += 1
  elif pair == "RS":
    count_RS += 1
  elif pair == "RN":
    count_RN += 1
  elif pair == "NR":
    count_NR += 1
  elif pair == "NS":
    count_NS += 1
  else:
    print(pair)
    print(i)

# Print
print(f"SS count: {count_SS}")
print(f"SR count: {count_SR}")
print(f"SN count: {count_SN}")
print(f"RR count: {count_RR}")
print(f"RS count: {count_RS}")
print(f"RN count: {count_RN}")
print(f"NR count: {count_NR}")
print(f"NS count: {count_NS}")

"""For each distinct combination, the number of occurrences and the total for each weather condition are presented below:

Total **S**: 191
  - **SS**: 95
  - **SR**: 49
  - **SN**: 47

Total **R**: 204
  - **RR**: 101
  - **RS**: 46
  - **RN**: 57

Total **N**: 104
  - **NR**: 55
  - **NS**: 49

**Methodology**:

To determine the number of days in a 30-day month with varying weather conditions, we employ two key variables. The transitional matrix, represented as **P**, encapsulates the probabilities of transitioning from one weather condition to another, calculated by dividing the number of occurrences by the total of each specified weather condition. Additionally, the initial distribution, denoted as **D0**, reflects the initial proportions of normal (**N**), rainy (**R**), and snowy (**S**) days in a 30-day month period.
  - **N** days: 7/30,
  - **R** days: 7/30,
  - and **S** days: 16/30.

We initialize a variable, **D**, to the initial distribution **D0**. A loop is then executed 30 times,simulating the transitions over the course of a month. Within each iteration, the matrix multiplication operator '*@* ' is utilized to update **D** and represent the distribution of days after applying the transition probabilities defined in the transitional matrix **P**.
"""

import numpy as np

# Transition matrix
P = np.array([[0, 55/104, 49/104],
              [57/204, 101/204, 46/204],
              [47/191, 49/191, 95/191]], dtype=np.float64)

# Initial distribution based on the first 30 days of given 500
D0 = np.array([7/30, 7/30, 16/30], dtype=np.float64)

# Iterate 30 times to simulate 30 days
D = D0
for _ in range(30):
    D = D @ P  # Matrix multiplication

print(D)

"""**Results**:

After calculating the resulting distribution, we add the outputs to verify if the result is 1. This verification ensures that the outputs are accurate. Once we've checked the summation of the outputs, we multiply each output by 30, representing the proposed 30-day month. This multiplication provides us with the number of nice (**N**), rain (**R**), and snow (**S**) days in the Land of Oz during a 30-day month.

This script simulates the changing distribution of days throughout a month in the Land of Oz, leveraging a transitional matrix to model the probabilities of transitioning between different weather conditions. The resulting distribution, obtained after 30 iterations, provides valuable insights into the expected weather patterns based on the defined probabilities.
"""